### ISSUE TITLE
Kein Connect über Pixel Watch 

### ISSUE THREAD

**Issue by coyote9999** [Schnup89/ioBroker_WearV2#12]
Habe die APK über ADB installiert.
Den Websocket Adapter auf Port 8084 eingestellt.

Grüner Haken in der Watch App wechselt ständig vom roten X zum grünen Haken.
Protokoll des ioBrokers läuft voll. (s. Screenshot)

Aktuelle ioBroker Installation auf VM.
Hatte jemand diesen Fehler schonmal?

LG

![2023-02-04 20_05_54-logs - ioBrokerVM](https://user-images.githubusercontent.com/15721437/216785273-cb93b691-f572-4392-b831-3d7b79041eec.png)

**Comment by Schnup89** [comment]
Hey,

verbinde mal deine Uhr per WLAN und deaktiviere Bluetooth. 

Gruß

**Comment by coyote9999** [comment]
Hey :)

Leider keine Änderung.
ioBroker Protokoll läuft weiterhin voll.
Beenden muss erzwungen werden, damit keine Anfragen mehr gesendet werden.

**Comment by Schnup89** [comment]
Ok, welche websocket Version läuft auf deinem iobroker?
Ich versuche es morgen nachzustellen

**Comment by coyote9999** [comment]
Danke!

WebSocket Version 1.3.0
Node.js: v14.19.3(14.21.2 / 16.19.0)
NPM: 6.14.9(6.14.17 / 8.19.3)

**Comment by Schnup89** [comment]
Beim nachstellen habe ich zwei Fehler-Szenarien gefunden, die seit dem Wechsel auf Websockets noch abzufangen sind.

1. (Für dein Problem irrelevant) Bei Falscher URL oder nicht erreichbaren Websockets bleibt der Splash-Screen stehen
2. Wenn der Name der Aufzählung falsch geschrieben ist, versucht die App ständig neu zu verbinden ohne Fehlermeldung.

-> Das 2. Problem dürfte bei dir der Fall sein, schau mal ob die Groß und Kleinschreibung passt wie auf dem Bild:

![image](https://user-images.githubusercontent.com/28166743/216828086-c66f8259-08b6-4ca0-9ee3-6ad8840d9b50.png)

**Comment by coyote9999** [comment]
Hi!

Das 2. Problem war tatsächlich die Lösung.
Besten Dank!

**Comment by Schnup89** [comment]
Perfekt, danke dir für die Rückmeldung.
Bin gerade dabei den Fehler abzufangen und eine Fehlermeldung zu implementieren.

https://github.com/Schnup89/ioBroker_WearV2/issues/13
