### ISSUE TITLE
2. Button steuert falsches Gerät an.

### ISSUE THREAD

**Issue by coyote9999** [Schnup89/ioBroker_WearV2#14]
Hi nochmal :)

Möchte 2 Buttons anlegen.
Aber es wird immer das 2. Objekt ausgelöst.
Auf der Uhr leuchten dann beide Buttons kurz auf, egal welchen Button man drückt.

![image](https://user-images.githubusercontent.com/15721437/216831751-ef5d2a86-aea0-4797-a4e6-d108aa97f80c.png)

1. Objekt:
![image](https://user-images.githubusercontent.com/15721437/216831773-fb5b5aa6-50c5-460a-9012-af0dca0d3a50.png)

2. Objekt:
![image](https://user-images.githubusercontent.com/15721437/216831798-caf6a23f-6126-4a7f-9515-c0d21bf3b391.png)

**Comment by Schnup89** [comment]
Kann ich nachstellen ✓
Fix kommt mit dem nächsten Update

**Comment by Schnup89** [comment]
Problem wurde mit V2.9 gelöst.

https://github.com/Schnup89/ioBroker_WearV2/commit/e908164b20875587ea7dc794b43e20590d2df067

**Comment by Schnup89** [comment]
Warte auf Rückmeldung bevor Issue geschlossen wird

**Comment by coyote9999** [comment]
Rückmeldung positiv :)
Fehler ist behoben.
