### ISSUE TITLE
Please add the example pictures to README.md

### ISSUE THREAD

**Issue by GermanBluefox** [Schnup89/ioBroker_WearV2#16]
![image](https://user-images.githubusercontent.com/4582016/217196589-1595ac23-23c8-474b-90e6-fc9143104dd7.png)

**Comment by GermanBluefox** [comment]
![wearos2](https://user-images.githubusercontent.com/4582016/217198678-c82a9b03-53a4-4472-ada1-0ffc9cb38ab4.gif)

**Comment by Schnup89** [comment]
Thank you very much! 
https://github.com/Schnup89/ioBroker_WearV2/commit/a3ecf0f851745ec75b321f5358c32de749cf5131
