### ISSUE TITLE
Unterwegs nutzbar machen

### ISSUE THREAD

**Issue by braindead1** [Schnup89/ioBroker_WearV2#2]
Das ist ein sehr interessantes Projekt. Gibt es Pläne das Ganze unabhängig zu machen vom eigenen WLAN und so zu ermöglichen den ioBroker von unterwegs zu steuern?

**Comment by Schnup89** [comment]
Dafür müsste man den ioBroker im Internet veröffentlichen oder es über einen VPN Tunnel über das Smartphone testen.
Beides habe ich leider nicht konfiguriert und kann es nicht nachstellen, wobei ersteres aufgrund der Sicherheit deines Systems nicht zu raten ist.
In der Theorie ist es jetzt schon möglich wenn du als Server Adresse in der app deinen öffentlichen dns/ip adresse mit passendem port forwarding einträgt, aber wie gesagt, securitymäßig ist das nichts.

Wie kommst du aktuell an den ioBroker von unterwegs?

**Comment by braindead1** [comment]
Ich habe vor 2 Jahren mal testweise an einem Adapter gearbeitet der den ioBroker mit einer Google Firebase verbunden hat (https://github.com/braindead1/ioBroker.firebase). Ziel war es damals die Historie dort zu speichern. Eigentlich müsste beides "nur" miteinander verbunden werden.

**Comment by Schnup89** [comment]
Das würde heißen dass der Firebase Adapter die states/Objekte "live" ausliest und online in der Firebase Cloud speichert.als json mit allen werten.
Die uhr müsste dann parallel dazu die Werte aus der Cloud auslesen.

Hab ich das richtig verstanden?

**Comment by braindead1** [comment]
Kennst Du die Android App ioGo? Die macht es exakt so. Firebase wird als Schnittstelle zwischen ioBroker und Android genutzt. Hier der Link zum Adapter: https://github.com/nisiode/ioBroker.iogopro. 

Leider plant der Entwickler von ioGo keine Wear OS App.

**Comment by Schnup89** [comment]
Habe es mir eben angesehen.
Der "Umbau" würde eine grundlegende Überarbeitung des Code mit sich ziehen, von daher kann ich das leider nicht umsetzen.
Evtl. könnte man den Code von hier in die iogopro app übernehmen um diese damit "Wear-Fähig" zu machen, aber das müsste dann der Entwickler der App tun.

**Comment by Schnup89** [comment]
Habe gerade die Option mit dem VPN getestet, funktioniert ohne Probleme.
Einfach vom SmartPhone aus ein VPN zu deinem Heimnetz aufbauen, die App wird dann über den SmartPhone-Bluetooth-Proxy eine Verbindung über den VPN Tunnel zum ioBroker aufbauen.
