### ISSUE TITLE
Galaxy watch 6 classic keine URL Eingabe

### ISSUE THREAD

**Issue by Jetiman** [Schnup89/ioBroker_WearV2#20]
Hi,

ich bin auf die Galaxy Watch 6 classic gewechselt.
Wenn ich auf den URL Button drücke kommt nur ein schwarzer Screen. Ich kann somit nichts eingeben.

**Comment by Schnup89** [comment]
Ich denke die Watch 6 hat schon das neue Betriebssystem.
Sobald die watch 4 das Update bekommt kann ich das nachstellen.

**Comment by Rushmed** [comment]
Same here. Wenn ich auf den Button zur URL Eingabe gehe kommt nur ein schwarzer Bildschirm der sich nach rechts wegswipen lässt.

**Comment by Jetiman** [comment]
Versuch mal die Google Tastatur. Ich nutze SwiftKey. Damit war der Fehler. Ich meine mit der Samsung oder gboard gings dann.

**Comment by Rushmed** [comment]
Sehr guter Tipp, danke. Ich hatte Gboard schon voreingestellt. Nach dem Wechsel auf die Samsung Tastatur gings.

**Comment by Schnup89** [comment]
Danke für eure Hinweise, ich setze mich die Tage hin und aktualisiere die App und die Uhr auf aktuelle Lib's.

**Comment by Toki99** [comment]
Nun habe ich es mit der Samsung Tastatur probiert. Seitdem ist das Display weiß auf der Uhr den ich die Wear IOB starte

**Comment by Schnup89** [comment]
Hallo zusammen,
bitte einmal testen bitte, durch die neuen libs sollte das Problem gelöst sein:
APK:
https://github.com/Schnup89/ioBroker_WearV2/releases/tag/v2.9.1
Changes:
https://github.com/Schnup89/ioBroker_WearV2/commit/3f786ae7205c5ad343dd1782799c2fae8267d0b4

**Comment by Jetiman** [comment]
Sieht gut aus. Funktioniert soweit

**Comment by Schnup89** [comment]
Danke für die schnelle Rückmeldung!
