### ISSUE TITLE
[Feature request] Benachrichtigung wenn Ereignis eingetreten ist

### ISSUE THREAD

**Issue by Toki99** [Schnup89/ioBroker_WearV2#21]
Hallo Tobias, tolles Sache diese Anbindung. Ist es irgendwie möglich, das ein Nachricht an die Uhr gesendet wird, wenn bzw. ein Tür Kontakt in ioBroker geöffnet wird?

**Comment by Schnup89** [comment]
Hey, da die App nicht ständig die Verbindung zu ioBroker hält ist dies über diese App nicht zu realisieren.

Du kannst trotzdem Alarme auf den Smartphone empfangen mit der Pushover App: https://pushover.net/


Einfach anmelden, API Keys erzeugen und den Anleitungen des gleichnamigen ioBroker Adapter folgen.

**Comment by Schnup89** [comment]
Hi, seit September 2023 unterstütz die Pushover-App WearOS:
https://play.google.com/store/apps/details?id=net.superblock.pushover&hl=de_AT
Damit kann deine Anforderung besser umgesetzt werden.
