### ISSUE TITLE
URL kann nicht eingeben werden

### ISSUE THREAD

**Issue by ckoop** [Schnup89/ioBroker_WearV2#24]
Hi,

ich habe die APP v2.9.1 installiert auf dein Samsung Watch 4  installiert. Kann aber die URL nicht eingeben. Wenn ich auf das Feld klicke, kommt nur ein schwarzes Bild. Zurück auf den Startscreen der App ist aber kein Problem.

Gruss

**Comment by Jetiman** [comment]
Versuch einmal die Tastertur von Samsung auf das gboard zu stellen.

**Comment by Schnup89** [comment]
> Versuch einmal die Tastertur von Samsung auf das gboard zu stellen.

@ckoop: Hat das funktioniert? Wenn ja würde ich einen Hinweis auf der Hauptseite erstellen

**Comment by ckoop** [comment]
Ja, hat funktioniert. Es war aber vom gboard zur Samsung Tastatur und nicht anders herum.
