### ISSUE TITLE
For Values ICONS are not shown

### ISSUE THREAD

**Issue by Flying-Bolt** [Schnup89/ioBroker_WearV2#25]
For values, I do not display icons, but only black squares.
![Object](https://github.com/Schnup89/ioBroker_WearV2/assets/12726678/6bfb42ec-d475-4108-bb96-0554b7c0f2fa)

**Comment by Schnup89** [comment]
Hi, funktioniert das gleiche Symbol bei Tastern? Somit könnten wir zumindest die Grafik als Fehlerquelle ausschließen.

Generell gab es in den letzten Versionen keine Anpassungen im Code für die Icons, der Fehler müsste dann schon länger drin sein.

**Comment by Flying-Bolt** [comment]
Bei Tastern funktioniert es, d.h. gleiches ICON nur die Rolle z.B. nach "scene.states" ändern, dann wird das ICON angezeigt
![CaptureIObroker](https://github.com/Schnup89/ioBroker_WearV2/assets/12726678/1c45a05e-50d2-4745-8f06-60a1a2084a74)
[
![Uhr](https://github.com/Schnup89/ioBroker_WearV2/assets/12726678/a3f39011-0553-4a86-bf87-3b2366f8225a)
](url)

**Comment by Flying-Bolt** [comment]
Gibt es schon was neues zu diesem Problem?

**Comment by Flying-Bolt** [comment]
ich das Projekt ins Android Studio geladen und im Layout Inspector kann man erkennen, dass das icon verdeckt wird. Es ist also da, aber verdeckt. Ich vermute das es beim aktiven chip nicht geladen ist.
![prtscr](https://github.com/user-attachments/assets/607fc9d9-4095-411a-8f02-51e5623a27b6)

**Comment by Flying-Bolt** [comment]
Habe das Problem selbst gelöst und mir auch eine eigene Variante estellt.

I solved the problem myself and also created my own variant.
